sonar.projectKey=card-delivery-hub
sonar.projectName=CardDeliveryHub
sonar.projectVersion=1.0.0-SNAPSHOT

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.coveragePlugin=jacoco

sonar.exclusions=\
  **/CardDeliveryHubApplication.java,\
  **/domain/dto/**,\
  **/domain/entity/**,\
  **/domain/enums/**,\
  **/config/**,\
  **/messaging/event/**

sonar.coverage.exclusions=\
  **/CardDeliveryHubApplication.java,\
  **/domain/dto/**,\
  **/domain/entity/**,\
  **/domain/enums/**,\
  **/config/**,\
  **/messaging/event/**
